"""empty message

Revision ID: 04cd49def103
Revises: 67f47767d889
Create Date: 2018-04-08 17:52:44.690052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04cd49def103'
down_revision = '67f47767d889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IDC', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('IDC', sa.Column('last_modify_time', sa.DateTime(), nullable=True))
    op.add_column('auth', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('auth', sa.Column('last_modify_time', sa.DateTime(), nullable=True))
    op.drop_column('auth', 'addtime')
    op.add_column('group', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('group', sa.Column('last_modify_time', sa.DateTime(), nullable=True))
    op.drop_column('group', 'addtime')
    op.add_column('host_group', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('host_group', sa.Column('last_modify_time', sa.DateTime(), nullable=True))
    op.add_column('loginlog', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.drop_column('loginlog', 'addtime')
    op.add_column('network_device', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('network_device', sa.Column('last_modify_time', sa.DateTime(), nullable=True))
    op.add_column('role', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('role', sa.Column('last_modify_time', sa.DateTime(), nullable=True))
    op.drop_column('role', 'addtime')
    op.add_column('storage', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('storage', sa.Column('last_modify_time', sa.DateTime(), nullable=True))
    op.add_column('tag', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('tag', sa.Column('last_modify_time', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_modify_time', sa.DateTime(), nullable=True))
    op.drop_column('user', 'addtime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('addtime', mysql.DATETIME(), nullable=True))
    op.drop_column('user', 'last_modify_time')
    op.drop_column('user', 'create_time')
    op.drop_column('tag', 'last_modify_time')
    op.drop_column('tag', 'create_time')
    op.drop_column('storage', 'last_modify_time')
    op.drop_column('storage', 'create_time')
    op.add_column('role', sa.Column('addtime', mysql.DATETIME(), nullable=True))
    op.drop_column('role', 'last_modify_time')
    op.drop_column('role', 'create_time')
    op.drop_column('network_device', 'last_modify_time')
    op.drop_column('network_device', 'create_time')
    op.add_column('loginlog', sa.Column('addtime', mysql.DATETIME(), nullable=True))
    op.drop_column('loginlog', 'create_time')
    op.drop_column('host_group', 'last_modify_time')
    op.drop_column('host_group', 'create_time')
    op.add_column('group', sa.Column('addtime', mysql.DATETIME(), nullable=True))
    op.drop_column('group', 'last_modify_time')
    op.drop_column('group', 'create_time')
    op.add_column('auth', sa.Column('addtime', mysql.DATETIME(), nullable=True))
    op.drop_column('auth', 'last_modify_time')
    op.drop_column('auth', 'create_time')
    op.drop_column('IDC', 'last_modify_time')
    op.drop_column('IDC', 'create_time')
    # ### end Alembic commands ###
