"""empty message

Revision ID: 4624d910268f
Revises: 4ad7de5ae2e7
Create Date: 2018-04-02 14:47:26.444668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4624d910268f'
down_revision = '4ad7de5ae2e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('server_id', sa.Integer(), nullable=True))
    op.drop_constraint('assets_ibfk_1', 'assets', type_='foreignkey')
    op.create_foreign_key(None, 'assets', 'server', ['server_id'], ['id'])
    op.drop_column('assets', 'servers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('servers', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.create_foreign_key('assets_ibfk_1', 'assets', 'server', ['servers'], ['id'])
    op.drop_column('assets', 'server_id')
    # ### end Alembic commands ###
