"""empty message

Revision ID: 4ad7de5ae2e7
Revises: cce10e036327
Create Date: 2018-04-02 14:40:02.831714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ad7de5ae2e7'
down_revision = 'cce10e036327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('device_model_id', sa.Integer(), nullable=True))
    op.drop_constraint('server_ibfk_1', 'server', type_='foreignkey')
    op.create_foreign_key(None, 'server', 'device_model', ['device_model_id'], ['id'])
    op.drop_column('server', 'device_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('device_model', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'server', type_='foreignkey')
    op.create_foreign_key('server_ibfk_1', 'server', 'device_model', ['device_model'], ['id'])
    op.drop_column('server', 'device_model_id')
    # ### end Alembic commands ###
