"""empty message

Revision ID: 500be08c9931
Revises: 5d07efdba5bb
Create Date: 2018-04-09 14:06:14.259179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500be08c9931'
down_revision = '5d07efdba5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('device_type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'device_type')
    # ### end Alembic commands ###
