"""empty message

Revision ID: 634a4e09cdae
Revises: f134c6a80270
Create Date: 2018-04-02 17:28:22.880972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634a4e09cdae'
down_revision = 'f134c6a80270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor', sa.Column('address', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor', 'address')
    # ### end Alembic commands ###
