"""empty message

Revision ID: a581a55b18b7
Revises: bd9d04100487
Create Date: 2018-04-03 16:10:13.507584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a581a55b18b7'
down_revision = 'bd9d04100487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('IDC', 'name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('assets', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('auth', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('auth', 'url',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('device_model', 'name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('group', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('host_group', 'name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('role', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('server', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('server', 'sn_number',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('tag', 'name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('tag', 'name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('server', 'sn_number',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('server', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('role', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('host_group', 'name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('group', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('device_model', 'name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('auth', 'url',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('auth', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('assets', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('IDC', 'name',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
