"""empty message

Revision ID: cce10e036327
Revises: 
Create Date: 2018-04-02 14:39:27.797226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce10e036327'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url')
    )
    op.create_table('device_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('vender_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['vender_id'], ['device_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('is_admin', sa.String(length=32), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('host_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('remark', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('is_admin', sa.String(length=32), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('remark', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.String(length=32), nullable=True),
    sa.Column('is_admin', sa.String(length=32), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('remark', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups_roles',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.create_table('loginlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('operation_type', sa.String(length=32), nullable=True),
    sa.Column('ip', sa.String(length=128), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_auths',
    sa.Column('auth_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['auth_id'], ['auth.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.create_table('server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sn_number', sa.String(length=256), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('device_model', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('cpu_name', sa.String(length=32), nullable=True),
    sa.Column('cpu_count', sa.SmallInteger(), nullable=True),
    sa.Column('memory', sa.String(length=32), nullable=True),
    sa.Column('memory_count', sa.SmallInteger(), nullable=True),
    sa.Column('disk', sa.String(length=32), nullable=True),
    sa.Column('disk_count', sa.SmallInteger(), nullable=True),
    sa.Column('RAID_type', sa.String(length=32), nullable=True),
    sa.Column('network_card_type', sa.String(length=32), nullable=True),
    sa.Column('network_card_count', sa.String(length=32), nullable=True),
    sa.Column('power_count', sa.SmallInteger(), nullable=True),
    sa.Column('ip_address', sa.String(length=256), nullable=True),
    sa.Column('mac_address', sa.String(length=256), nullable=True),
    sa.Column('system_version', sa.String(length=128), nullable=True),
    sa.Column('remark', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['device_model'], ['device_model.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_groups',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('users_roles',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('assets_number', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('use', sa.String(length=64), nullable=True),
    sa.Column('nature', sa.String(length=32), nullable=True),
    sa.Column('servers', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('last_modify_time', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['servers'], ['server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hostgroups_servers',
    sa.Column('host_group_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['host_group_id'], ['host_group.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], )
    )
    op.create_table('IDC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('assets_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['assets_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets_tags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('assets_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assets_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets_tags')
    op.drop_table('IDC')
    op.drop_table('hostgroups_servers')
    op.drop_table('assets')
    op.drop_table('users_roles')
    op.drop_table('users_groups')
    op.drop_table('server')
    op.drop_table('roles_auths')
    op.drop_table('loginlog')
    op.drop_table('groups_roles')
    op.drop_table('vendor')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('role')
    op.drop_table('host_group')
    op.drop_table('group')
    op.drop_table('device_model')
    op.drop_table('auth')
    # ### end Alembic commands ###
