"""empty message

Revision ID: f134c6a80270
Revises: 4624d910268f
Create Date: 2018-04-02 14:51:53.469162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f134c6a80270'
down_revision = '4624d910268f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_model', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.drop_constraint('device_model_ibfk_1', 'device_model', type_='foreignkey')
    op.create_foreign_key(None, 'device_model', 'vendor', ['vendor_id'], ['id'])
    op.drop_column('device_model', 'vender_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_model', sa.Column('vender_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'device_model', type_='foreignkey')
    op.create_foreign_key('device_model_ibfk_1', 'device_model', 'device_model', ['vender_id'], ['id'])
    op.drop_column('device_model', 'vendor_id')
    # ### end Alembic commands ###
