"""empty message

Revision ID: f5b13d63c689
Revises: bfb957b7f1ed
Create Date: 2018-04-08 17:11:40.704140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5b13d63c689'
down_revision = 'bfb957b7f1ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'server_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('server_model', mysql.VARCHAR(length=128), nullable=False))
    # ### end Alembic commands ###
